"""empty message

Revision ID: c7cddceb832e
Revises: d9238ebd4301
Create Date: 2017-02-10 20:25:19.404467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cddceb832e'
down_revision = 'd9238ebd4301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'e_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'products', ['e_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'e_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
